version: "3"
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env.local
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env.local
